name: CI
'on':
  push:
    branches:
      - main
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      # Checkout the Repo
      - uses: actions/checkout@v2

      # Install Node 17
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 17

      # Install dependencies
      - run: npm ci

      # Run tests
      - run: npm test
